#version: '3.9'
#
#services:
#  postgres:
#    image: postgres:16-alpine
#    container_name: instory_db
#    environment:
#      POSTGRES_USER: instory
#      POSTGRES_PASSWORD: instory_pass
#      POSTGRES_DB: Instory
#    ports:
#      - "5432:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#
#volumes:
#  pgdata:


version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    container_name: instory_db
    environment:
      POSTGRES_USER: instory
      POSTGRES_PASSWORD: instory_pass
      POSTGRES_DB: Instory
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      
  api:
    build: 
      context: ./backend  
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  
    environment:
      - ConnectionStrings__Instory=Host=postgres;Database=Instory;Username=instory;Password=instory_pass
    depends_on:
      - postgres
    volumes:
      - dataprotection_keys:/root/.aspnet/DataProtection-Keys

volumes:
  pgdata:
  dataprotection_keys: