@InstoryAPI_HostAddress = http://localhost:5174

// Register a new user
POST {{InstoryAPI_HostAddress}}/api/v1/auth/register
Content-Type: application/json

{
  "username": "testusername",
  "email": "testemail@gmail.com",
  "password": "testpassword",
  "fullName": "Test User"
}
###
// Login with the registered user
POST {{InstoryAPI_HostAddress}}/api/v1/auth/login
Content-Type: application/json

{
  "usernameOrEmail": "testusername",
  "password": "testpassword"
}


