@InstoryAPI_HostAddress = http://localhost:5174

GET {{InstoryAPI_HostAddress}}/api/v1/posts/feed?pageNumber=1&pageSize=5
###
GET {{InstoryAPI_HostAddress}}/api/v1/posts/1

### Create Post with Images
POST {{InstoryAPI_HostAddress}}/api/v1/posts
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="Content"

test post
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="AllowComment"

true
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="Images"; filename="test.png"
Content-Type: image/png

< ./test-image.webp
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
POST {{InstoryAPI_HostAddress}}/api/v1/posts/1/like

###
DELETE  {{InstoryAPI_HostAddress}}/api/v1/posts/comments/5
