@InstoryAPI_HostAddress = http://localhost:5174


GET {{InstoryAPI_HostAddress}}/api/v1/story

###

GET {{InstoryAPI_HostAddress}}/api/v1/story/1

###
POST {{InstoryAPI_HostAddress}}/api/v1/story
Content-Type: application/json

{
  "UserId": 3,
  "MediaUrl": "abc",
  "Caption": "abc"
}

###
DELETE {{InstoryAPI_HostAddress}}/api/v1/story/1

###
POST {{InstoryAPI_HostAddress}}/api/v1/auth/login
Content-Type: application/json

{
  "usernameOrEmail": "mindang",
  "password": "mindang"
}

###
GET {{InstoryAPI_HostAddress}}/api/v1/profile/quocbao

###
PATCH {{InstoryAPI_HostAddress}}/api/v1/profile/me
Content-Type: application/json

{
  "username": "mindang1"
}




